
target-version = "py310"
fix = true

[lint]
extend-select = [
    "B",
    "C90",
    "E501",  # line too long (default 88)
    "I",  # isort
    "UP",  # pyupgrade
]
extend-safe-fixes = ["UP008"]
exclude = ["setup/*"]

[format]
exclude = ["setup/*"]

[lint.per-file-ignores]
"__init__.py" = ["F401", "I001"]
"__manifest__.py" = ["B018"]
"complete_i18n.py" = ["E501", "F601"]
"export_i18n.py" = ["E501"]
"fix_i18n.py" = ["E501"]
"l10n_ve_reports/**/*.py" = ["E501", "C901", "E402", "B007", "B018", "B008", "B023", "E741", "B904", "E721", "E722", "F823", "B020", "F402", "F811", "UP031", "UP038"]
"l10n_ve_fiscal_serial/static/src/fdm.py" = ["E501", "C901", "E402", "B904", "E721", "E722"]
"l10n_ve_edi_tfhka/**/*.py" = ["E501", "C901", "UP038"]
"l10n_ve_igtf/**/*.py" = ["E501", "C901"]
"l10n_ve_withholding/**/*.py" = ["E501", "E741", "B023"]
"l10n_ve_bank_statement_import/**/*.py" = ["E501", "C901"]
"l10n_ve_payment_advance/**/*.py" = ["E501"]
"l10n_ve_pos_igtf/**/*.py" = ["E501", "E741"]
"l10n_ve_reports_stock/**/*.py" = ["E501", "C901"]
"l10n_ve_seniat/**/*.py" = ["E501", "C901"]
"l10n_ve_vat_seniat/**/*.py" = ["E501", "C901"]
"l10n_ve_audit/**/*.py" = ["E501"]
"l10n_ve_fiscal_serial/**/*.py" = ["E501", "C901", "E402", "B904", "E721", "E722", "F811", "B007"]
"l10n_ve_fiscal_serial_pos/**/*.py" = ["E501"]
"l10n_ve_invoice_escp/**/*.py" = ["E501", "C901"]
"l10n_ve_igtf/wizard/**/*.py" = ["E741"]
"l10n_ve_edi/**/*.py" = ["E501"]
"l10n_ve_seniat_sale/**/*.py" = ["E501"]
"l10n_ve_stock/**/*.py" = ["E501"]
"l10n_ve_pos/**/*.py" = ["E501"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "odoo", "odoo-addons", "first-party", "local-folder"]

[lint.isort.sections]
"odoo" = ["odoo"]
"odoo-addons" = ["odoo.addons"]

[lint.mccabe]
max-complexity = 16
