from odoo import _, api, fields, models
from odoo.exceptions import ValidationError


class ResCompany(models.Model):
    _inherit = "res.company"

    l10n_ve_igtf_currency_ids = fields.Many2many(
        comodel_name="res.currency",
        relation="l10n_ve_igtf_res_company_currency_rel",
        column1="company_id",
        column2="currency_id",
        string="IGTF Currencies",
        help="Currencies for which IGTF should apply (for example, USD).",
    )

    l10n_ve_igtf_account_id = fields.Many2one(
        comodel_name="account.account",
        string="IGTF Account",
        check_company=True,
        domain=[("account_type", "=", "liability_payable")],
        help="Payable account used to record IGTF generated by payments.",
    )
    l10n_ve_igtf_percent = fields.Float(
        string="IGTF (%)",
        default=3.0,
        help="IGTF percentage to split from the payment and post to the IGTF account.",
    )

    @api.constrains("l10n_ve_igtf_percent")
    def _check_l10n_ve_igtf_percent(self):
        """
        Validate that the configured IGTF percentage is within a valid range.

        Parameters
        ----------
        None

        Returns
        -------
        None

        Raises
        ------
        ValidationError
            If IGTF percentage is outside the [0, 100] interval.
        """
        for company in self:
            if (
                company.l10n_ve_igtf_percent < 0.0
                or company.l10n_ve_igtf_percent > 100.0
            ):
                raise ValidationError(_("IGTF percentage must be between 0 and 100."))
