{
    "name": "Currency POS",
    "version": "18.0.1.0.0",
    "category": "Point of Sale",
    "sequence": 10,
    "summary": "Currency conversion for products in Point of Sale",
    "author": "andyengit,Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/l10n-venezuela",
    "license": "LGPL-3",
    "images": [],
    "depends": [
        "point_of_sale",
        "l10n_ve_product_currency",
    ],
    "data": [],
    "assets": {
        "point_of_sale._assets_pos": [
            "currency_pos/static/src/app/generic_components/currency_rates_widget/currency_rates_widget.xml",
            "currency_pos/static/src/app/generic_components/currency_rates_widget/currency_rates_widget.js",
            "currency_pos/static/src/app/screens/product_screen/product_screen.js",
            "currency_pos/static/src/app/screens/product_screen/product_screen.xml",
            "currency_pos/static/src/overrides/store/pos_store.js",
            "currency_pos/static/src/overrides/models/pos_order.js",
            "currency_pos/static/src/overrides/models/product_product.js",
            "currency_pos/static/src/overrides/components/orderline/orderline.js",
            "currency_pos/static/src/overrides/components/orderline/orderline.xml",
            "currency_pos/static/src/overrides/components/order_widget/order_widget.js",
            "currency_pos/static/src/overrides/components/order_widget/order_widget.xml",
            "currency_pos/static/src/overrides/components/control_buttons/control_buttons.js",
            "currency_pos/static/src/overrides/components/control_buttons/control_buttons.xml",
            "currency_pos/static/src/overrides/screens/payment_screen/payment_screen.js",
            "currency_pos/static/src/overrides/screens/payment_screen/payment_screen.xml",
            "currency_pos/static/src/overrides/components/product_card/product_card.js",
            "currency_pos/static/src/overrides/components/product_card/product_card.xml",
        ],
    },
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": False,
}
